### ISSUE TITLE
Side bar links not working

### ISSUE THREAD

**Issue by zzPolarix** [Haptic-Apps/Slide#2722]
Slide version: v5.8.5
Android version: 7.1
The side bar links on some subreddit just takes me back to the subreddit's homepage rather than where it should bring me.

**Comment by ccrama** [comment]
Do you have any examples of a subreddit with links that don't work?

**Comment by zzPolarix** [comment]
These links are an example from r/tekken

**Comment by ccrama** [comment]
Hmm I've never seen links formatted like that before, interesting (@Alexendoo thoughts?)

**Comment by Alexendoo** [comment]
They're absolute paths e.g. `/r/Tekken/699xxr/`, don't know any other example but it makes sense, would need to resolve it with reddit.com as the host name

**Comment by ccrama** [comment]
Yeah should be super easy by just matching the comments regex without the actual "comments" string in it

**Comment by Tensounder54** [comment]
> /r/Tekken/699xxr/

Yeah it appears that this is sill an issue for /r/tekken. It's only this link and it looks like @ccrama and @Alexendoo have come up with a solution. If it doesn't get solved soonish I'll take a look.
