### ISSUE TITLE
Side panel can't be opened with gesture on Android 10 due to gestural navigation conflicts.

### ISSUE THREAD

**Issue by QuickBASIC** [Haptic-Apps/Slide#3017]
Slide version: Slide v6.2
Android version: Android Q Beta 3 10 (QPP 3190404015)

Issue: Doing the gesture to open side panel (sliding from left) when gestural navigation is enable instead exits Slide (back button).

Requesting that developers add exception for left side for Back gesture to Slide so that panel can still be opened with gesture as described here.

https://developer.android.com/preview/features/gesturalnav#conflicting-gestures

**Comment by Tensounder54** [comment]
This is definitely something that we need to look into. IDK if Q is in full release yet. If it is then this needs to be jumped on ASAP.

**Comment by QuickBASIC** [comment]
Android Q is still in beta.

@chrisbanes has said the behavior is changing in Android Q Beta 5.

https://twitter.com/chrisbanes/status/1146050918892412928?s=19

**Comment by Alexendoo** [comment]
Now that it's out (I think) does it still conflict @QuickBASIC?

**Comment by gitfib** [comment]
It does when using the new gestures. Peeking doesn't work well when there's an image in the same area (it'll try to do both), and it's not intuitive anyway

It might be enough to just update the relevant libraries
