### ISSUE TITLE
Cannot set a brand new flair (have to already have one set, then i can change it)

### ISSUE THREAD

**Issue by Rose-David** [Haptic-Apps/Slide#3019]
Slide version: 6.2
Android version: 9

**Comment by Targetednuke** [comment]
If this is an API limitation, thats cool, but if its a bug, please fix it

**Comment by Tensounder54** [comment]
I'm not sure what could be causing this. @timawesomeness Any ideas?

**Comment by teknolog1k** [comment]
Closing as development is on indefinite hiatus. If development restarts, and the issue is still present, then I can reopen it.
