### ISSUE TITLE
Persistent connection issues

### ISSUE THREAD

**Issue by 894-572** [Haptic-Apps/Slide#3155]
When the app has been on idle for essentially any period of time, content won't load anymore and killing the app is necessary. Always connects when restarted. May be related to weak or losing a wi-fi connection.

Slide version: 6.3
Android version: 9 (LineageOS 16)

logcat filtered by the app's PID `23919`: [logcat_04-20-2020_15-20-37.txt](https://github.com/ccrama/Slide/files/4503454/logcat_04-20-2020_15-20-37.txt)

**Comment by ghost** [comment]
Closing the issue, I don't use the app anymore nor did I after creating the issue to any real degree. May not have been reproducible.
