### ISSUE TITLE
Picture mode setting keeps switching to "big picture"

### ISSUE THREAD

**Issue by strout** [Haptic-Apps/Slide#3421]
Several times now I have set the picture mode in settings to "no thumbnails" and later find it has reverted to "big picture". ~~So far I don't have consistent reproduction steps, but I've hit it several times over the last few days.~~ Steps to reproduce:

1. In post layout settings, set picture mode = no thumbnails.
2. Quit with the back button and reopen the app: the setting is still effective.
3. Close the app by swiping up on the app switcher and reopen: the setting is back to "big picture".

Slide version: 6.7.1 (from F-Droid)
Android version: 9 (on a Samsung Galaxy S8)

**Comment by MelinEss** [comment]
Hello, if it is okay for you, Can I work on this issue? Thank you.

**Comment by Alexendoo** [comment]
Sure, @MelinEss
