### ISSUE TITLE
Unable to open "reddit.com" links by default

### ISSUE THREAD

**Issue by worsedoughnut** [Haptic-Apps/Slide#3429]
Slide version: 6.7.1
Android version: 12

After updating to Android 12, Slide is only able to add the following as default supported links:
"amp.reddit.com"
"redd.it"

Attempting to add use the "Add link" option, does not list "reddit.com" as a possible option as shown in the attached image.

![image](https://user-images.githubusercontent.com/9027176/141332081-9dc423c1-39ba-4afb-88b0-fec4ab409e2a.png)

This makes it so any normal reddit link, found in a google search for example, will always open in the default browser rather than Slide. This was not an issue in Android 11.

**Comment by Forbo** [comment]
Having the ability to open `www.reddit.com`, `old.reddit.com`, and `i.reddit.com` links would be awesome.

**Comment by utack** [comment]
I am not sure why but when I click "open with app" after clicking those links in Firefox it sends me to Slide
How can that happen, if reddit,com links are not linked to Slide in Android 12?

**Comment by Alexendoo** [comment]
Maybe 12 doesn't like the `*reddit` part, might need to be replaced with separate entries for `reddit.com`, `*.reddit.com`, `npreddit.com` (used internally)

**Comment by Alexendoo** [comment]
#3439

**Comment by utack** [comment]
We have had Android 12 for a while now, it would be nice to get a fix for daily use. Is there any update on the horizon that includes it?

**Comment by TacoTheDank** [comment]
@utack Perhaps, though it won't be available on the Play Store because of technical issues regarding their requirements.
