### ISSUE TITLE
App will not load any content, spinning circle

### ISSUE THREAD

**Issue by ioogithub** [Haptic-Apps/Slide#3440]
Slide version: 6.7.1
Android version: Android 11

App was working successfully earlier in the day. When I opened it this afternoon, no content will load.

Subreddits are shown but content does not load. Same results for both Guest and with an account.

I cleared data and cache, reinstalled app as a test, no change.

**Comment by Alexendoo** [comment]
Reddit is currently slow/failing to load sometimes on desktop as well, so it's likely an issue upstream. If it's still happening tomorrow LMK

**Comment by manuelrepo** [comment]
had the same problem, but it was gone afterwards
couldn't find a way to reproduce it outside of the slide app neither inside of slide after that short timeframe
this can be closed imo

**Comment by Alexendoo** [comment]
👍 if it's still happening please reopen
