### ISSUE TITLE
Slide keeps accessing the clipboard for seemingly no reason

### ISSUE THREAD

**Issue by JakeHL** [Haptic-Apps/Slide#3461]
Slide version: 6.7.1
Android version: 12

I keep getting toast notifications telling me that slide has pasted from the android clipboard. This happens randomly and I am unable to get it to happen consistently (apart from actually pasting of course)

this is a huge security risk and id advise everyone stops using slide until this is fixed.

**Comment by Alexendoo** [comment]
It's not a security risk, it's an old feature that offers to open a reddit link if you have one on your clipboard

https://github.com/Haptic-Apps/Slide/blob/9d72ccede1d64ec5ca1fa7fe8622f2543a4de120/app/src/main/java/me/ccrama/redditslide/Activities/MainActivity.java#L1196-L1220

Back then there were no indicators for clipboard access, nowadays it may be worth removing because of that

**Comment by JakeHL** [comment]
This is absolutely a security risk. regardless of the intention, its still reading the clipboard without any consent from the user.

**Comment by Alexendoo** [comment]
The code is right there... you can see exactly what it does, which is nothing bad

**Comment by tmjwid** [comment]
To replicate, have a fresh item in the clipboard, load an image then swipe back out and it triggers the clipboard. I too was worried when I first saw this as I had just used a password from my password manager so I spent a good hour profiling the app to see if any network traffic happened when clipboard was triggered. Nothing did but still, it's shouldn't be done in the background with no user notification.

**Comment by tmjwid** [comment]
> There is an api to read clipboard so apps use it to provide features, what the point of having a clipboard if you dont use it? You could have checked the source or searched posts about it in 1 minute instead, also no serious password manager use the clipboard as it's not secure or they offer it as alternative and you have to enable manually + it warn you about using it, they use the autofill framework or in rare cases where autofill isn't working some have a special keyboard to input password, also i'm reading that since android 11 they can integrate with the default keyboard https://developer.android.com/guide/topics/text/ime-autofill but idk if any password manager use it already.

I did check the source as well as profile the app. Nothing wrong with some extra due diligence just in case I missed something and I felt it was warranted at the time as this feature isn't listed anywhere to my knowledge and it was a bit of a shock. I do agree with you about clipboard security and I am now fixing that with autofill like you mentioned.

**Comment by JakeHL** [comment]
closing as the maintainer seems to have no interest in addressing the issue. I've moved to infinity instead.

**Comment by karate** [comment]
I understand that this was build for the iOS version. Is it supposed to work for Android as well? Links in the clipboard don't load automatically for me in Android 12 with Slide 6.7.1.
